const express = require('express')
const app = express()
require('./DB/init')
const path = require('path')
const film= require('./DashboardSide/Film')
const football= require('./DashboardSide/Football')
const series= require('./DashboardSide/Series')
const routeclint = require('./AdminRoute/adminroute')
const serversideAdmin = require('./ServerAdminSide/Admin')
const static = path.join(__dirname,'./Public')
const views = path.join(__dirname ,'./Views')
app.set('view engine','hbs')
app.set('views',views)
app.use(express.static(static))
app.use(express.json())
app.use(routeclint)
app.use(serversideAdmin)
app.use(film)
app.use(series)
app.use(series)
app.use(football)

 
app.listen(process.env.PORT || 3000)